package gitlab

import (
	"fmt"
	"testing"
)

func TestParseMRs(t *testing.T) {
	json_str := `[{"id":9,"iid":1,"project_id":15,"title":"fix typo","description":"","state":"merged","created_at":"2021-02-25T02:00:30.664Z","updated_at":"2021-02-25T02:00:45.166Z","merged_by":{"id":2,"username":"lisong","name":"Li Song","state":"active","avatar_url":"http://gitlab.qitantech.com/uploads/-/system/user/avatar/2/avatar.png","web_url":"http://gitlab.qitantech.com/lisong"},"merge_user":{"id":2,"username":"lisong","name":"Li Song","state":"active","avatar_url":"http://gitlab.qitantech.com/uploads/-/system/user/avatar/2/avatar.png","web_url":"http://gitlab.qitantech.com/lisong"},"merged_at":"2021-02-25T02:00:45.294Z","closed_by":null,"closed_at":null,"target_branch":"master","source_branch":"debug","user_notes_count":0,"upvotes":0,"downvotes":0,"author":{"id":2,"username":"lisong","name":"Li Song","state":"active","avatar_url":"http://gitlab.qitantech.com/uploads/-/system/user/avatar/2/avatar.png","web_url":"http://gitlab.qitantech.com/lisong"},"assignees":[{"id":2,"username":"lisong","name":"Li Song","state":"active","avatar_url":"http://gitlab.qitantech.com/uploads/-/system/user/avatar/2/avatar.png","web_url":"http://gitlab.qitantech.com/lisong"}],"assignee":{"id":2,"username":"lisong","name":"Li Song","state":"active","avatar_url":"http://gitlab.qitantech.com/uploads/-/system/user/avatar/2/avatar.png","web_url":"http://gitlab.qitantech.com/lisong"},"reviewers":[],"source_project_id":15,"target_project_id":15,"labels":["bug"],"draft":false,"work_in_progress":false,"milestone":null,"merge_when_pipeline_succeeds":false,"merge_status":"can_be_merged","sha":"f958a025ee93c3bb28c63f2f6d73deb92170e66a","merge_commit_sha":"de69c427819b1083e488ebbf5d0b11a2a08d6b4d","squash_commit_sha":null,"discussion_locked":null,"should_remove_source_branch":null,"force_remove_source_branch":true,"reference":"!1","references":{"short":"!1","relative":"!1","full":"lisong/auto-run!1"},"web_url":"http://gitlab.qitantech.com/lisong/auto-run/-/merge_requests/1","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"squash":false,"task_completion_status":{"count":0,"completed_count":0},"has_conflicts":false,"blocking_discussions_resolved":true,"approvals_before_merge":null}]`
	mrs := ParseMRs([]byte(json_str))
	fmt.Printf("%+v", mrs)
}

func TestParseIssue(t *testing.T) {
	json_str := `{"id":1033,"iid":17,"project_id":102,"title":"Changes of v3.0.1","description":"## Changes\n\n- [!19](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/19) Update .gitlab-ci.yml by Li Song\n- [!18](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/18) Update .gitlab-ci.yml by Li Song\n- [!17](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/17) Update .gitlab-ci.yml by Li Song\n- [!15](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/15) Update .gitlab-ci.yml by Li Song\n- [!13](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/13) Update .gitlab-ci.yml by Li Song\n- [!6](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/6) Update .gitlab-ci.yml by Li Song\n- [!5](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/5) Update .gitlab-ci.yml by Li Song\n- [!4](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/4) 修改模板 by Li Song\n- [!3](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/3) 测试 templates by Li Song\n- [!2](http://gitlab.qitantech.com/playground/projecta/-/merge_requests/2) Update .gitlab-ci.yml by Li Song","state":"opened","created_at":"2022-05-07T04:43:46.126Z","updated_at":"2022-05-07T04:43:46.126Z","closed_at":null,"closed_by":null,"labels":[],"milestone":null,"assignees":[],"author":{"id":46,"username":"project_102_bot","name":"test","state":"active","avatar_url":"https://www.gravatar.com/avatar/813572d6ac1cb6ebb71d29f824072b6a?s=80\u0026d=identicon","web_url":"http://gitlab.qitantech.com/project_102_bot"},"type":"ISSUE","assignee":null,"user_notes_count":0,"merge_requests_count":0,"upvotes":0,"downvotes":0,"due_date":null,"confidential":false,"discussion_locked":null,"issue_type":"issue","web_url":"http://gitlab.qitantech.com/playground/projecta/-/issues/17","time_stats":{"time_estimate":0,"total_time_spent":0,"human_time_estimate":null,"human_total_time_spent":null},"task_completion_status":{"count":0,"completed_count":0},"weight":null,"blocking_issues_count":0,"has_tasks":false,"_links":{"self":"http://gitlab.qitantech.com/api/v4/projects/102/issues/17","notes":"http://gitlab.qitantech.com/api/v4/projects/102/issues/17/notes","award_emoji":"http://gitlab.qitantech.com/api/v4/projects/102/issues/17/award_emoji","project":"http://gitlab.qitantech.com/api/v4/projects/102"},"references":{"short":"#17","relative":"#17","full":"playground/projecta#17"},"subscribed":true,"moved_to_id":null,"service_desk_reply_to":null,"epic_iid":null,"epic":null}`
	mrs := ParseIssue([]byte(json_str))
	fmt.Printf("%+v", mrs)
}
