site: gitlab.com # maybe different for your instance
project: 31285645 # replace by your own project ID
branch: master
post: true
token: xxxxxxxxxxx # replace by your own token
start_tag: v1.0.0
end_tag: v1.0.1